version: 2

sources:
  - name: landing                 # Source name
    database: ready-de26                   # GCP Project
    schema: project_landing                # BigQuery dataset
    tables:
      - name: orders_landing_abdelrahman
      - name: order_items_landing_abdelrahman
      - name: order_reviews_landing_abdelrahman
      - name: products_landing_abdelrahman
      - name: product_category_name_translation_landing_abdelrahman
      - name: customers_landing_abdelrahman
      - name: geolocation_landing_abdelrahman
      - name: leads_closed_landing_abdelrahman
      - name: leads_qualified_landing_abdelrahman
      - name: sellers_landing_abdelrahman
      - name: order_payments_landing_abdelrahman
