version: 2

models:
  - name: dim_customers
    tests: [unique, not_null]
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: dim_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: dim_sellers
    columns:
      - name: seller_id
        tests: [not_null, unique]

  - name: fact_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id

  - name: fact_order_items
    columns:
      - name: order_id
        tests:
          - relationships:
              to: ref('fact_orders')
              field: order_id

  - name: fact_payments
    columns:
      - name: order_id
        tests:
          - relationships:
              to: ref('fact_orders')
              field: order_id
